### ISSUE TITLE
Make Starred Album Public?

### ISSUE THREAD

**Issue by seonwoolee** [LycheeOrg/Lychee-Laravel#47] opened 2018-11-17 04:06 UTC
How can I make the Starred album public? I can make all my starred photos public, but the starred album still isn't public

**Comment by ildyria** [comment] 2019-06-21 22:58
@kamil4 while you are at it... :laughing:

**Comment by kamil4** [comment] 2019-06-22 02:50
Heh... When I was implementing public Recent I asked myself this question: should any others be public as well? Starred could be but I figured that nobody would want to since in publicMode we don't even display the stars (though stars do influence the album thumbs).

I guess somebody does want to after all. Oh well, shouldn't be too much work to add. The front end should actually be good as I made that part fully generic but the server will need changes, of course.

**Comment by kamil4** [comment] 2019-06-26 03:48
Closed via #293.

**Closed by kamil4** 2019-06-26 03:48 UTC
Labels: enhancement

**Comment by ckizer** [comment] 2019-09-06 00:56
I'm completely confused. I imported 200 images. How can I make them all public? How can I set an album to be public? The only thing I see is i have to click on each image 1 by 1 add it to a new public album. This will take about 6 weeks.

**Comment by ckizer** [comment] 2019-09-06 00:58
How do I make an album public? I can't figure out any settings for this? 
<img width="409" alt="Screen Shot 2019-09-05 at 5 57 49 PM" src="https://user-images.githubusercontent.com/191738/64393525-b9f91200-d006-11e9-8a5f-e25a56c246fb.png">

**Comment by kamil4** [comment] 2019-09-06 03:36
I don't believe that you are using Lychee-Laravel (v4), but rather the current git HEAD of Lychee v3. Which, I can confirm, appears to be broken; I'll fix that. In the meantime, however, I would strongly recommend that you actually do try Lychee-Laravel. We just released version 4 beta 1, which you can find [here](https://github.com/LycheeOrg/Lychee-Laravel/releases/tag/v4.0.0-beta.1).

In the non-broken version, clicking on the leftmost eye icon brings up a dialog window where you can make an album public by clicking on the large slider.

Also, in the future, please open a new issue rather than adding unrelated comments to issues that are already closed.
