### ISSUE TITLE
[Enhancement] Display disk space usage

### ISSUE THREAD

**Issue by matthiasbe** [LycheeOrg/Lychee-Laravel#269] opened 2019-06-03 12:36 UTC
Hi,

I've installed this project at home on a Raspberry Pi to share photos with my family. It's a really nice tool so far, great job for that :+1:

I have a limited amount of disk space, so I would like to see how much disk space is used by media on my instance of Lychee, so that I can expect when I need to extend the available space.

Is it possible to have this information on the current version ?

**Comment by kamil4** [comment] 2019-06-03 15:59
Well, we do store the size of each full-size image in the database, so in principle it wouldn't be too hard to cobble something together to count them, but I think to make it _truly useful_, it will be more work.

A big issue is that we don't store the sizes of the generated intermediate images (thumb/small/medium and their 2x variants) anywhere.

Another is that the size of each full-size image is stored in the database in human-readable form (exactly as you see it displayed in the "Info" sidebar for each image, with "KB" and "MB" suffixes) so it's not very accurate and the error will accumulate if we add them up.

Frankly, I'm not sure of the value of storing image sizes in the database at all. I don't think it would be a stretch to obtain it at run time in photo view (we don't really need it in the album view I think?) and I think this is how we should do it for the intermediate sizes if we implement this feature.

I'm going to reference issue #226 from here just so that we have a cross-reference. It's not a duplicate of this one, but they are related, so when solving one we could consider solving the other one at the same time. As to where it should be displayed, I think that we should enable the info sidebar also at the top-level albums view and provide such information there.

**Comment by d7415** [comment] 2019-06-03 19:13
I'd almost be more tempted to add an on-demand call to `du`/`df` (or, ideally, an interface to them to avoid shelling out). `du` can be slow though, so if we did do that we'd want to be careful where we put it (or fetch it, at least) if we went down that path.

**Comment by matthiasbe** [comment] 2019-06-04 07:33
There is also [this PHP function](https://www.php.net/manual/en/function.disk-free-space.php) which could fit, at least in my use case.

**Closed** 2019-06-05 10:48 UTC
Labels: enhancement
