### ISSUE TITLE
Test User connection (for non admin)

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#196] opened 2019-04-13 22:15 UTC
Also check if albums diplays.

As #192 showed, we also need this test.

**Comment by jprokop1** [comment] 2019-04-14 09:19
I have set up users for testing purposes:

![image](https://user-images.githubusercontent.com/46556236/56090622-e61fc500-5ea4-11e9-8697-9b85403d0c28.png)

Album Test1 & Test1_Subalbum created by admin, subalbum_user1 created by user1.
Sharing:

![image](https://user-images.githubusercontent.com/46556236/56090644-267f4300-5ea5-11e9-895d-5838858879c1.png)

And behavior:
user1 - visible Test1 (with pictures) and subalbum_user1; not visible Test1_Subalbum
user2 - visible only Test1 (with pictures) 
user3 - visible only Test1 (with pictures) 
user4 - visible only Test1 (with pictures) 

All with postgresql as backend, I'll try it with mysql
I hope it helps

**Comment by jprokop1** [comment] 2019-04-14 09:29
MySQL - the same.
Interesting - even if the subalbum_user1 is not visible, thumb is from this album (was added as last)

**Comment by ildyria** [comment] 2019-04-14 12:32
> Interesting - even if the subalbum_user1 is not visible, thumb is from this album (was added as last)

yeah it is still leaking. The sub album part is tricky to manage in that case. :)

**Comment by kamil4** [comment] 2019-05-21 03:10
@jprokop1 Could you please test again with the current HEAD?

The thumb leaking should definitely be fixed as of last night, and I can't reproduce the sharing issue either.

Note that two things have changed in the meantime:

1. An ordinary user can no longer create a subalbum in an album belonging to another user.
2. If the admin creates a subalbum in another user's album, that subalbum will be owned by that other user, not the admin.

Those changes may affect the outcome of the test. The old behavior, where we could have albums with mixed ownership of the content, was determined to be a bug.

**Comment by jprokop1** [comment] 2019-05-21 07:14
I started testing, the first issues:
user1 may try to write a description for the Test1 album (owned by admin), the description will appear in the box but an error will appear: 
`2019-05-21 06:56:17 -- error   -- App\Http\Middleware\UploadCheck::album_check -- 113 -- Could not find specified album`
and the description is not in the database.
Another problem - user1 may try to upload a new image to the Test1 album, the system will hang and the same error in the log: 
`2019-05-21 06:56:17 -- error   -- App\Http\Middleware\UploadCheck::album_check -- 113 -- Could not find specified album` 
Can this be related to previous settings? Do you suggest testing on a new clean install?

**Comment by ildyria** [comment] 2019-05-21 09:31
No this is normal. This is more of a front end problem.

The way we do it is :
- look for an album with the given albumID and where the owner of the album is the userID. So if you do not own such album, then it will obviously not be found. I can understand that the error does not make sens but this is just a shortcoming of the front end.

**Comment by jprokop1** [comment] 2019-05-21 13:42
Sharing between users seems to work properly for me after a quick behavior test - this can be closed. There was still a bug (as in #143) - cannot selectively delete sharing, the "remove" button will delete everything

**Closed** 2019-09-17 13:51 UTC
Labels: CI
