### ISSUE TITLE
Corrupt zip archive created when album size is >4GB

### ISSUE THREAD

**Issue by quigybo** [LycheeOrg/Lychee-Laravel#331] opened 2019-09-07 19:05 UTC
### Detailed description of the problem
The zip archive created using the download album button is corrupt when the (compressed) size of the album is >4GB.

### Steps to reproduce the issue
1. Go into an album which is >4GB
2. Click on 'Download Album'
3. Try to extract the downloaded zip archive

Output when trying to unzip archive (on a 64bit Arch Linux machine):
```
$ unzip --help
UnZip 6.00 of 20 April 2009, by Info-ZIP.
$ unzip album.zip 
Archive:  album.zip
warning [album.zip]:  4294967296 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  4294967296
  (attempting to re-compensate)
checkdir error:  album.zip exists but is not directory
                 unable to process album.zip/DSC_6733.jpg.
...
checkdir error:  album.zip exists but is not directory
                 unable to process album.zip/DSC_8335.jpg.
file #381:  bad zipfile offset (local header sig):  3957486
  (attempting to re-compensate)
checkdir error:  album.zip exists but is not directory
                 unable to process album.zip/DSC_8336.jpg.
...
```
The exit status of `unzip` is `2`.

I was able to recover the archive with (credits [here](https://stackoverflow.com/a/31485014)):
```
$ zip -FF album.zip --out album_repaired.zip -fz
```

### Output of the diagnostics
I know the version is moderately old, but I prefer not to update the running instance to test if the issue is still current.
```
    Diagnostics
    -----------
    Warning: Dropbox import not working. No property for dropboxKey.

    System Information
    ------------------
    Lychee-front Version:    3.2.14
    Lychee Version (git):    262dc31 (master) - Probably more than 30 commits behind master
    DB Version:              040000
    System:                  Linux
    PHP Version:             7.3
    MySQL Version:           8.0.16
    Imagick:                 1
    Imagick Active:          1
    Imagick Version:         1690
    GD Version:              2.2.5

    Config Information
    ------------------
    version:                 040000
    checkForUpdates:         0
    sortingPhotos_col:       takestamp
    sortingPhotos_order:     ASC
    sortingAlbums_col:       description
    sortingAlbums_order:     DESC
    imagick:                 1
    skipDuplicates:          0
    small_max_width:         0
    small_max_height:        360
    medium_max_width:        1920
    medium_max_height:       1080
    lang:                    en
    layout:                  1
    image_overlay:           1
    image_overlay_type:      exif
    default_license:         none
    compression_quality:     90
    full_photo:              1
    deleteImported:          1
    Mod_Frame:               0
    Mod_Frame_refresh:       30000
    landing_page_enable:     0
    landing_owner:           ---
    landing_title:           ---
    landing_subtitle:        
    landing_facebook:        
    landing_flickr:          
    landing_twitter:         
    landing_instagram:       
    landing_youtube:         
    landing_background:      
    thumb_2x:                1
    small_2x:                0
    medium_2x:               0
    site_title:              ---
    site_copyright_enable:   0
    site_copyright_begin:    2019
    site_copyright_end:      2019
    additional_footer_text:  
    display_social_in_gallery: 0
```

### Browser and system
* Lychee-Laravel-Docker at commit a300383f
* Docker image bigrob8181/lychee-laravel dev (at 262dc31)
* Docker image mysql v8.0

**Comment by kamil4** [comment] 2019-09-07 21:48
An album with >4GB of photos? You don't mess around. :wink:

The whole download feature went through an overhaul in commit 7ccd77f379be461d88b7c64a9047d865396f7628 (merged on July 11). Given that, it would be good to know if the problem is still present, though to be perfectly honest, I expect that it's still there.

We use a third party package for generating zip files and I expect the bug to be with them; I'll see if a newer version than the one we use mentions fixing such a problem...

**Comment by kamil4** [comment] 2019-09-07 22:51
Huh... By the look of it, upstream has it fixed at the price of losing compatibility with MacOS:

https://github.com/maennchen/ZipStream-PHP/commit/6cdd417699fe89cdc4925f4d6fd811f30b1628fd

We should probably upgrade but we'll need to add a config to either support 64bit zips or the native MacOS unarchiver...

**Closed** 2019-09-26 12:08 UTC
Labels: bug, upstream
