### ISSUE TITLE
Photo sorting "by upload date" does not work correctly

### ISSUE THREAD

**Issue by ABLomas** [LycheeOrg/Lychee-Laravel#300] opened 2019-07-08 07:33 UTC
I have set sort "by upload date" from very beginning, but some photos ignore this rule. This happens with older versions (at least 5 months old), too, so this is not new issue/regression. Photo sorting happens on upload and easy to notice when new photo does not appear on top, but instead goes into middle/bottom of album.
Example album: https://pics.lag.lt/#15519937717252 - scroll to bottom and check upload dates on last photos. Ilustrated:
![lychee_photo_dates](https://user-images.githubusercontent.com/8989151/60791039-7d767a80-a16b-11e9-9feb-28f7fc1d3352.jpg)

I checked EXIF but can't spot anything suspicious on badly sorted photos - they are taken with different cameras, processed with the same software. EXIF should be available in "Full Photo" view.
Also this happens on multiple albums.

**Comment by ildyria** [comment] 2019-07-08 11:27
It looks like they are ordered by ID instead of `takestamp`.

**Comment by kamil4** [comment] 2019-07-08 15:12
This looks like a duplicate of #123, which I fixed on March 22. Have you not updated your installation in a while? E.g., I see that https://pics.lag.lt/#15519937717252/1559810316064 is affected even though it was uploaded on June 6th.

The current version should not exhibit this problem. However, the already uploaded pictures are affected. @ABLomas the easiest fix would be to re-upload the whole album with the current version, in the desired order. If you are comfortable messing around with the SQL console though, I can send you the queries that will fix it for the four pictures affected without re-uploading anything.

@ildyria `ID` and `takestamp` are basically supposed to be the same; it's just that `ID` is easier to sort by so that's what we use :-).

**Comment by ABLomas** [comment] 2019-07-08 15:21
My running code is not very old, i think around 1 week or so (updated after "Public smart albums (#293)" commit).
I'm fine with photo ordering if new photos will appear in correct order. Searched before opening issue, but missed this one, probably because you were talking about albums and i had issues with photos.
Give me few days, if photos will go in correct order, i will close this issue.

**Closed** 2019-07-21 08:31 UTC
Labels: duplicate
